signal={
'Inverse of Market Value'
'Earning to Price Ratio'
'Book to Market Ratio'
'1-month Momentum'
'3-months Momentum'
'12-months Momentum'
'Return on Assets'
'Return on Equity'
'Leverage'
'Current Ratio'
'Cash Ratio'
'Asset Torunover'
'Equity Tournover'
'Revision Ratio'
'3-months FY1 Estimate Change'
'12-months FY1 Estimate Change'
};