%% !!!!!!!!!!!!!!!!!!!!!!!!!!! VERY IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

% TO RUN THIS CODE (WHICH RUNS OTHER CODES) YOU NEED TO INSTAL THE SPATIAL
% ECONOMETRIX TOOLBOX (WHICH IS PROVIDED IN THE ZIP FILE WE SENT YOU).
% SPECIFICALLY, YOU WILL NEED THE SPATIAL ECONOMETRIX TOOLBOX TO BE ABLE TO
% RUN THE VERY LAST CODE (risk.m), IN WHICH WE ESTIMATE VOLATILITY USING
% THE EXPONENTIAL SMOOTHING MODEL


%% !!!!!!!!!!!!!!!!!!!!!!!!!!! VERY IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

% WE SUGGEST THAT YOU RUN THE CODE PIECE BY PIECE, THIS FOR 2 REASONS:

% - CODES ARE A BIT HEAVY, DESPITE WE CLEARED THE UNUSED VARIABLES EVERY TIME.
% - ALSO, SOME CODES WILL PRODUCE A BIG AMOUNT OF GRAPHS, THAT YOU WILL
% NEED TO CLOSE


%% !!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

% WE NEVER USED THE XLSWRITE FUNCTION FOR INCOMPATIBILITY PROBLEMS WITH OUR
% OPERATING SYSTEMS, SO OUTPUTS WERE PROVIDED ON EXCEL JUST COPYING AND
% PASTING THE RESULTS OPENING THE VARIABLES IN THE WORKSPACE


%% UPLOADING THE DATASET AND MAKING THE FIRST TRANSFORMTION

run datatrans


%% PLOT THE BENCHMARK AND SOME GRAPHS TO GET A VISUAL OF THE ACTUAL BEHAVIOUR OF THE INDUSTRIES

run datatrans_graphs


%% CHOOSING THE SIGNALS TO USE (AND TRY A DYNAMIC MODEL)

run signals

%% ASSESSING THE GOODNES OF OUR DYNAMIC MODEL

run signals_dynamic

%% FINAL CHOICE OF THE SIGNALS

run signals_choice

%% FORECASTING THE SIGNALS AND PORTFOLIO IMPLEMENTATION

run forecasting


%AND

run portfolio130 % PORTFOLIO WITH TRACKING ERROR=0.04
% !!!!!! CHECK IN THE COMMAND WINDOW IF THE CODE IS ACTUALLY RUNNING !!!!!!

% OR

% run portfolio130_1 % PORTFOLIO WITH TRACKING ERROR=0.01

%% RISK MEASURES, RISK-ADJUSTED PERFORMANCE MEASURE, EX-POST PANEL REGRESSION

run risk

%% BACK-TESTING

run forecast_back

%AND

run portfolio130_back % PORTFOLIO WITH TRACKING ERROR=0.04

% OR

% run portfolio130_1_back % PORTFOLIO WITH TRACKING ERROR=0.01



