signal={
'Inverse of Market Value'
'Earning to Price Ratio'
'Book to Market Ratio'
'1-month Momentum'
'3-months Momentum'
'12-months Momentum'
'Return on Assets'
'Return on Equity'
'Leverage'
'Current Ratio'
'Cash Ratio'
'Asset Torunover'
'Equity Tournover'
'Revision Ratio'
'3-months FY1 Estimate Change'
'12-months FY1 Estimate Change'
'Ind. Adj. Earning to Price'
'Ind. Adj. Book to Market'
'Ind. Adj. Return on Assets'
'Ind. Adj. Return on Equity'
'Ind. Adj. Leverage'
'Ind. Adj. Current Ratio'
'Ind. Adj. Cash Ratio'
'Ind. Adj. Asset Torunover'
'Ind. Adj. Equity Tournover'
'Ind. Adj. Revision Ratio'
'Ind. Adj. 3-months FY1 Est. Ch.'
'Ind. Adj. 12-months FY1 Est. Ch.'
};