funds={'Charter Fund'
'Blair (Wm) Fund'
'Financial Dynamics Fund'
'Activa Mutual Fund Trust: Mutual Fund'
'CG Fund'
'Dividend Shares'
'Chemical Fund'
'Quasar Associates Inc.'
'RCM Growth Equity Fund'
'AMCAP Fund'
'American Capital Exchange'
'Twentieth Century Growth Investors'
'Twentieth Century Income Investors'
'American Growth Fund'
'American Mutual Fund'
'Associated Fund Trust'
'Armstrong Associates Fund'
'INSTITUTIONAL INVESTORS CAPITAL APPRECIATION'
'LBKL Capital Opportunity Fund'
'Edie (Lionel D.) Capital Fund'
'Merrill Lynch Basic Value Fund'
'Merrill Lynch Special Value Fund (A)'
'Growth Industry Shares'
'Bridges Investment Fund'
'Herold Fund'
'Drexel Equity Fund'
'Loomis-Sayles Mutual Fund'
'Securities Fund'
'Century Shares Trust'
'Acorn Fund'
'Colonial Fund'
'Colonial Option Income Fund'
'Copley Fund'
'Country Capital Growth'
'Winthrop Focus--Growth And Income Fund'
'Neuwirth Fund'
'Balanced Income Fund'
'Kemper Option Income Fund'
'Television-Electronics Fund'
'Scudder Stevens & Clark Common Stock Fund'
'New York Venture Fund'
'Retirement Planning Funds of Amer--Equity'
'Delta Trend Fund'
'Delaware Income Fund'
'Delaware Fund'
'Dodge & Cox Stock Fund'
'Johnston Mutual Fund'
'Founders Mutual Fund'
'Natl Western Fund'
'Dreyfus Fund'
'Dreyfus Third Century Fund'
'Dreyfus Group Equity Fund'
'Eagle Growth Shares'
'Canada General Fund'
'Eaton & Howard Growth Fund'
'Elfun Trusts'
'Endowments, Inc.'
'Keystone S-4 (Lower Priced)'
'Keystone K-2 (Growth Fund)'
'Evergreen Total Return'
'Omega Fund'
'Transamerica Capital Fund'
'Paramount Mutual Fund'
'Pension Capital Growth Fund'
'Federated Capital Appreciation Fund/A'
'Fidelity Aggressive Income Fund'
'Fidelity Congress Street'
'Contrafund'
'Fidelity Destiny Fund'
'Fidelity Exchange Fund'
'Fidelity Fund'
'Magellan Fund'
'Puritan Fund'
'Fidelity Trend Fund'
'Fidelity Asset Investment Trust'
'SoGen Intl Fund'
'Franklin Dynatech Series'
'Franklin Custodian Funds--Income Series'
'Franklin Custodian Funds--Utilities Series'
'Franklin Custodian Funds--Common Stock'
'Winfield Growth Industries Fund'
'AGE Fund'
'Fundamental Investors'
'Mathers Fund'
'Mutual Investing Found--MIF Fund'
'Gateway Option Income Fund'
'General Electric S&S Program Fund'
'Growth Fund of America'
'M.S.B. Fund'
'Texas Fund'
'Imperial Capital Fund'
'Imperial Fund'
'Corporate Leaders Trust B'
'Goldfund, Inc.'
'Income Fund of America'
'Investment Co. of America'
'Janus Fund'
'Chancellor New Decade Growth Fund'
'Sovereign Investors'
'Shearson Appreciation Fund/A'
'Lehman Capital Fund'
'One William Street Fund'
'Affiliated Fund'
'Lord Abbett Developing Growth Fund'
'MFS Research Fund'
'Bascom Hill Investors'
'Mutual Benefit Fund'
'Mairs & Power Growth Fund'
'Mairs & Power Income Fund'
'Mass Investors Growth Stock Fund'
'Mass Investors Trust'
'InterCapital Industry-Valued Sec.'
'Mutual Shares Corp.'
'Mutual Qualified Income Fund'
'Beacon Investing Corp.'
'Mutual Investing Found--MIF Growth Fund'
'Neuberger & Berman Guardian Trust'
'Neuberger & Berman Manhattan Trust'
'Neuberger & Berman Partners Trust'
'Guardian Mutual Fund'
'Manhattan Fund'
'Side Fund'
'Energy Fund'
'New Perspective Fund'
'Nicholas Strong Fund'
'Northeast Investors Growth Fund'
'Analytic Optioned Equity Fund'
'Hamilton Income Fund'
'Hamilton Funds Series H-C7 & H-DA'
'Quest for Value Fund'
'Guardian Park Avenue Fund'
'Pax World Fund'
'Philadelphia Fund'
'Chase Fund of Boston'
'Phoenix Chase Stock Fund'
'National Sec.--Income Fund'
'Pioneer Fund'
'Pioneer II'
'Price (T. Rowe) Growth Stock Fund'
'Putnam Convertible Fund'
'Putnam Option Income Fund'
'Putnam Growth Fund'
'Incorporated Investors'
'Putnam Vista Fund'
'Putnam Voyager Fund/A'
'ADV Fund'
'Tudor Hedge Fund'
'IDS Growth Fund'
'Investors Variable Payment Fund'
'Axe-Houghton Fund B'
'Price (T. Rowe) New Era Fund'
'Price (T. Rowe) New Horizons Fund'
'Over-the-Counter Securities Fund'
'Pennsylvania Mutual Fund'
'American Natl Income Fund'
'Florida Mutual Fund'
'Security Equity Fund'
'Quarterly Distribution Shares'
'Security Ultra Fund'
'Selected American Shares'
'Selected Special Shares'
'Union Capital Fund'
'Broad Street Investing Corp'
'National Investors Corp.'
'Group Sec.--Common Stock Fund'
'Sentinel Growth Fund'
'Sequoia Fund'
'Spectra Fund'
'State Farm Income Fund'
'State Farm Growth Fund'
'National Industries Fund'
'Stratton Growth Fund'
'Templeton World Fund'
'Axe-Templeton Growth Fund of Canada'
'Lutheran Brotherhood Income Fund'
'USAA Capital Growth Fund'
'Valley Forge Fund'
'Value Line Fund'
'Value Line Income Fund'
'Value Line Leveraged Growth Fund'
'Value Line Special Situations Fund'
'Comstock Fund'
'California Fund'
'Provident Fund for Income'
'Fund of America'
'Kerr Income Fund'
'Pace Fund'
'Vanguard World--U.S. Growth'
'Explorer Fund'
'Morgan (W.L.) Growth Fund'
'Wellington Equity Fund'
'First Index Investment Trust'
'Naess & Thomas Special Fund'
'United Income Fund'
'Continental Fiduciary Shares'
'United Science Fund'
'United Vanguard Fund'
'United Continental Income Fund'
'United Accumulative Fund'
'Wall Street Investing Corp.'
'Washington Mutual Investors Fund'
'SIFE Trust Fund'
'Total Market'};